theme: jekyll-theme-slate
title: ğŸ’»âœ’ï¸ğŸ“„ğŸ’¡âœ…
description: Leonardo GurrÃ­a's CV

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: https://twitter.com/LeonardoGurria
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/leonardogurria/
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/leoga8